### ISSUE TITLE
crash when converting a post with JavaScript in it

### ISSUE THREAD

**Issue by BenLubar** [akhoury/bbcode-to-markdown#10]
Input:

``````
HTA app is currently this:
```
<HTML>
<HEAD>
   <HTA:APPLICATION
       ID="oHTA"
       APPLICATIONNAME="myApp"
       ICON="http://charlatanshanty.com/icon.ico">
<script type="text/javascript">
function show()
    {
    alert("show alert");
    }
    </script>
</head>
<body onload="show()">
</body>
</html>
```
``````

Expected output:
(unchanged)

Actual output:

```
HTA app is currently this:
\`\`\`
\`\`\`

TypeError: Cannot read property 'implementation' of undefined
    at Function.getListeners (/home/ben/discoconvert/akhoury-nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:176:74)
    at Function.dispatch (/home/ben/discoconvert/akhoury-nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:192:40)
    at Object.events.EventTarget.dispatchEvent (/home/ben/discoconvert/akhoury-nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/level2/events.js:287:33)
    at Object.DOMWindow.dispatchEvent (/home/ben/discoconvert/akhoury-nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:114:40)
    at /home/ben/discoconvert/akhoury-nodebb-plugin-import/node_modules/jsdom-nogyp/lib/jsdom/browser/index.js:50:16
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

**Comment by akhoury** [comment]
so it wasn't about the existence of a `<script>` tag in there, jsom-nogyp wasn't being able to build a DOM out of that HTML, , and I couldn't just `try/catch` the `window.close()` call, (which is what was causing the crash) because it's crashing asynchronously on the [nextTiçk](https://github.com/dexteryy/jsdom-nogyp/blob/04ab3885226f22df53c7dac8cca78606bd815ba5/lib/jsdom/browser/index.js#L49-L51)

We don't really need to use jsdom-gyp, it's just a fallback if to-markdown fails, so made that fallback method optional, if toMarkdown fails, it's probably for a good reason, the string will be returned un-converted, which is in your case a good idea, because that look like markdown to begin with.
